/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Paul
 */
public class UsuarioConectado extends javax.swing.JPanel {

    /**
     * Creates new form UsuarioConectado
     */
    public UsuarioConectado(String usuario) {
        initComponents();
        txtUsuario.setText("  "+usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 0, 0));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        setMinimumSize(new java.awt.Dimension(921, 100));
        setPreferredSize(new java.awt.Dimension(921, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(204, 0, 51));
        txtUsuario.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/conectado.png"))); // NOI18N
        txtUsuario.setText(" txtUsuario");
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 840, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
